### ISSUE TITLE
error retreiving accounts to block after 8500+

### ISSUE THREAD

**Issue by bubbles262** [satsukitv/twitter-block-chain#1]
hello. is there a maximum number of accounts we can block? i am trying to block someones 45k+ followers but every time it reaches around 8500, i get an error message saying twitter couldnt retrieve the rest of the accounts. its happened with two different high volume accounts. both times around the 8500 mark. it says to refresh and i do, and it once again stalls at that number. 
is there any way to help or circumvent this error or is it just too much? i really do wanna block all 45k people tho lol
thanks for the help!

**Comment by ceceradio** [comment]
@bubbles262 Thanks for reaching out! This is a known issue and is unfortunately very difficult to deal with. Twitter is either rate blocking the requests for followers or is limiting requests to the most recent 8500~ followers through the web interface API. The web interface API is the easiest for the plugin to use, as the rate limiting is very lenient for blocking users. It's also not documented, because it's technically only for Twitter to be using, not devs.

There does exist an API function to retrieve followers 5000 at a time: https://dev.twitter.com/rest/reference/get/followers/ids; however, utilizing that function requires real API credentials. I don't currently have a plan to tackle this issue due to the difficulty of utilizing the real Twitter API. I'm open to contributions on this issue!

**Comment by bubbles262** [comment]
thanks. that sucks. sigh. also, for some reason im able to block way more than 8500 if its the following tab, whereas the followers tab stalls there.

**Comment by ceceradio** [comment]
@bubbles262 yeah I believe the rate limiting applies to followers only, but again since the web interface API is undocumented it's difficult to know why or how to avoid the rate limit.

**Comment by cicifluff** [comment]
The first time I ran this, it blocked almost 170K accounts! Now I can only get up to 18K.  Is there something I can do differently to get more than 18K followers blocked?

**Comment by twilight-sparkle-irl** [comment]
Would it be possible to have it so that you could set your own API credentials?
