### ISSUE TITLE
ERROR AGAIN!!!

### ISSUE THREAD

**Issue by ghost** [satsukitv/twitter-block-chain#19]
Fuck you! I'm mad at you!
You are trying to fix the error?
I just thought that the error was fixed, and I'm getting an error again!?
Meh, Fuck It ALL!
I never use this garbage plugin anymore!

**Comment by gaeulbyul** [comment]
어떤 증상인지 구체적으로 얘기해주실 수 있나요? 사용하고 계시는 브라우저하고 버전도 알려주세요.

(Translate: Could you tell me for more detail about your problem? What browser/version are you using now?)

2018년 8월 3일 (금) 오후 7:39, blueheats416 <notifications@github.com>님이 작성:

**Comment by ghost** [comment]
됐슴다. 더는 이 엿같은 거 사용 안할라니께.

**Comment by gaeulbyul** [comment]
만약 웨일 브라우저를 쓰고 계신다면 그 브라우저가 버그있는 크로미움(버전 65)을 기반으로 만들어져서 체인블락이 작동하지 않을 수
있습니다. 이 경우엔 구글크롬이나 파이어폭스에서 사용하시면 잘 될겁니다.
이래도 안 된다면 비슷한 프로그램인 BlockThemAll이 있으니 이걸 써보세요. (윈도우즈 전용)
https://github.com/u1-liquid/BlockThemAll

(Translate: If you use Whale Browser, There is a known problem with Chromium 65 version (which Whale Browser based on it). In this case, try again with other browsers like Google Chrome or Firefox. Alternatively, There is another program called "BlockThemAll" for blocking someone's followers. https://github.com/u1-liquid/BlockThemAll  (Windows only))

2018년 8월 3일 (금) 오후 8:08, blueheats416 <notifications@github.com>님이 작성:

**Comment by unstabler** [comment]
@blueheats416 말 그런 식으로 하지 마세요. 아무런 댓가 없이 해당 플러그인을 개발해주신 개발자분께 실례란 생각은 안 드시는지요?

**Comment by ghost** [comment]
난 최대한 예의차려서 말한거요.
신뢰했던 플러그인이 이렇게 망가져서 화가 나는데 내가 말이 곱게 나오겠어? 사람 기분 빡치게 하지 말고 꺼져!

**Comment by channprj** [comment]
@github How can I report this kind of harassment in Github?

**Comment by saschanaz** [comment]
@channprj 어뷰즈 신고는 이 쪽에서 할 수 있습니다. https://github.com/contact/report-abuse

**Comment by saschanaz** [comment]
@channprj 어뷰즈 신고는 이 쪽에서 할 수 있습니다: https://github.com/contact/report-abuse

추신: 유저 프로파일 화면 왼쪽의 유저 이름 아래에도 신고 버튼이 있습니다.

Here is the form to report abuse: https://github.com/contact/report-abuse

Edit: You can also find the link in any user profile page, below the username.

**Comment by jtrimind** [comment]
@blueheats416 If you feel upset about this project, how about raise a PR?
Do not be rude. You don't make any maintenance contract with the project owner.

**Comment by simnalamburt** [comment]
@channprj You can report users with this button

<img width=200 src="https://user-images.githubusercontent.com/4435445/43673045-ae30283a-97f6-11e8-9857-521f199b7191.jpg">

@blueheats416  This project is licensed under MIT. No warranty is given and maintainers are not required to listen to users' support cases.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

@gaeulbyul @unstabler @saschanaz @jtrimind I'd really appreciate if you translate your comments into English for the others. This is the only issue which contains Korean and the owner of this project doesn't seem to be a Korean speaker to me.

**Comment by simnalamburt** [comment]
This project is licensed under MIT. No warranty is given and maintainers are not required to listen to users' support cases.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

**Comment by gaeulbyul** [comment]
@simnalamburt OK, I updated my comments into English.

**Comment by Alex4386** [comment]
@blueheats416

한 줄 요약:
이 코드 개발자는 MIT 라이선스에 의거해서 오류나도 고칠 이유가 없습니다. 근데 이렇게 기술지원을 해주는 것은 오히려 호의 인거죠. 그런 식으로 말씀하시지 마시죠. 만약 버그가 있는게 맘에 안드시면 포크 하신뒤 코드를 수정해서 버그를 고치시고 PR 걸어주시기 바랍니다.
This Program is licensed under MIT License, So It does NOT comes with warranty (ex. Tech Support, Bug fix). Do NOT think maintainer will fix it for you. if this bug makes you MAD, how about forking the repository and doing a Pull request?

라이선스 안읽어보셨나 봅니다.
I guess you did NOT read the LICENSE file

이 소프트웨어를 사용할때 라이선스에 동의하고 사용한다는게 규정화 되어 있는데도 말이죠.
Even though, If you use this program, you are agreeing with the license.

MIT 라이선스에는 이런 조항이 있습니다.
In the MIT License, There is a word.

이 프로그램은 워런티 없이 이 상태 그대로 제공됩니다.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

여기서 워런티는 기술지원을 포함한 오류픽스 등을 말합니다. (그러나 이건 오류도 아니죠. 크롬 자체의 버그니까요)
Yes. Indeed Warranty includes tech support or bug fixes. (But I guess your bug is not related to our code, since it seems like chromium-project's bug)

그러나 프로젝트 유지자 및 깃헙 사용자들이 지원을 해주니 그걸 당연한 것처럼 여기시는 분이 있습니다. (님 처럼요)
Even this project is using the license disclaims the warranty, project maintainer and github users are supporting the project. But It is not your right to get this service.

오픈소스 개발자들은 대개 직업으로 진행하는 프로젝트가 아닌이상 취미로하는 사람들이 많습니다. 아니 거의 대다수입니다. 이런 프로그램을 무료로 소스코드까지 공개해 주는것은 엄청난 호의죠.
They are supporting this project because these projects are hobbys for contributors unless the project is funded by major corporation. (Indeed, This is not the one funded by major corporation) And further more, Since this program is open source and is a free software, You download this program's source code free of charge and can edit this program for bug patch

그리고 한가지 말씀드리죠. 이 프로젝트가 오픈소스 프로젝트인 이상. 님이 직접 이 프로젝트를 포크 해서 직접 버그패치를 만들어서 지원 하실 수 있습니다. 만약 정말 화가 날 정도라면 버그를 직접 수정해서 PR을 내 주시기 바랍니다.
And One more thing, If you are really upset of this bug, try read the code and fix the error, And please if you fixed the error, give us a Pull request for code revises.

또한 버그리포트를 낼때는 화를 내는 것이 아니라 현재 사용중인 브라우저 버전 버그의 증상같은 기술적인 데이터 제공도 필요합니다. 화가 난다 만으로는 어디에서 버그가 났는지 알 수 없잖습니까.
And also, when you are writing bug report, calm down. And give us some technical information such as which version is your browser, what is the symptoms of the bug? We can not trace down the bug with the information such as I am upset :(

개발자들이 버그를 잡는 노력은 하겠지만 모든 환경에서의 버그를 잡는것은 어렵습니다.
Even, We are trying to fix the bug, It is nearly imporssible to fix the bug occurrs in different environments.

결론 적으로, 오픈소스 프로젝트에서 버그가 났다면, 버그를 고치기 힘든경우 Issue를 만들어 버그 상황에 대해 상세히 설명하거나 버그를 고칠 수 있는 경우 직접 프로젝트를 Fork하여 자신이 버그를 고쳐 PR을 보내세요.
In Conclusion, In opensource project and you occurred into bug, Create an issue with technical details when you can't fix it or fork the repo and fix the bug by yourself and give a Pull request.

여기까지 읽어주셔서 감사합니다.
Thank you for reading this article.
